# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import py_backwards.utils.helpers as module_0
import re as module_1
import py_backwards.exceptions as module_2


def test_case_0():
    int_0 = 264
    none_type_0 = module_0.debug(int_0)


def test_case_1():
    variables_generator_0 = module_0.VariablesGenerator()


def test_case_2():
    bool_0 = False
    callable_0 = module_0.eager(bool_0)


def test_case_3():
    var_0 = module_1.purge()
    module_0.get_source(var_0)


def test_case_4():
    str_0 = "URLError"
    none_type_0 = module_0.warn(str_0)


def test_case_5():
    none_type_0 = None
    callable_0 = module_0.eager(none_type_0)
    none_type_1 = module_0.debug(none_type_0)
    str_0 = "D'm6wpjff{5D#3"
    str_1 = "N"
    int_0 = 0
    compilation_error_0 = module_2.CompilationError(str_0, str_1, int_0, int_0)
    callable_0.__call__(
        callable_0, none_type_1, module=none_type_1, start=compilation_error_0
    )
